name: Release and Publish to Maven Central

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tagpr:
    permissions:
      actions: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.run-tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: run-tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: tagpr
    runs-on: ubuntu-latest
    if: needs.tagpr.outputs.tag != ''
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.tagpr.outputs.tag }}
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          server-id: ossrh
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
      - uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Publish signed artifacts
        run: mvn --batch-mode deploy -Dgpg.passphrase="${MAVEN_GPG_PASSPHRASE}"
